const buttonCss = "px-10 py-2 rounded";
export const primaryCss = `${buttonCss} bg-black text-white hover:bg-stone-700`;
export const secondaryCss = `${buttonCss} bg-gray-100 text-black hover:bg-gray-50`;
export const destructiveCss = `${buttonCss} bg-red-600 text-white hover:bg-red-500`;
export const outlineCss = `${buttonCss} bg-transparent text-black border-2 border-gray-200 hover:bg-gray-100`;
export const ghostCss = `${buttonCss} bg-transparent text-black hover:bg-gray-100`;
export const linkCss = `${buttonCss} bg-transparent text-black hover:underline`;
export const iconCss = `p-2 bg-gray-100 hover:bg-gray-50 border-2 border-gray-200`;
export const withIconCss = `p-3 bg-gray-100 hover:bg-gray-50 border-2 border-gray-200`;
